-- 妆友约：帖子图片 + 评论（文字/图片）
-- 用法：Supabase Dashboard → SQL Editor，整段粘贴执行（可重复执行）。
--
-- 说明：本站游客发帖采用「user_id 为空 + visitor_id 标识」的方式，
-- 因此评论表同样支持游客（user_id 为空）与登录用户两种身份。

-- 1) 帖子增加图片字段（imgbb 图床返回的图片地址）
alter table public.posts add column if not exists image_url text;

-- 2) 评论表
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  visitor_id text,
  author_name text,
  content text not null default '' check (char_length(content) <= 1000),
  image_url text,
  created_at timestamptz not null default now(),
  check (char_length(content) > 0 or image_url is not null),
  check (user_id is not null or visitor_id is not null)
);

create index if not exists comments_post_created_idx on public.comments (post_id, created_at);

-- 3) 行级安全策略
alter table public.comments enable row level security;

drop policy if exists "Anyone can read comments" on public.comments;
create policy "Anyone can read comments"
on public.comments for select
using (true);

drop policy if exists "Guests and users can create comments" on public.comments;
create policy "Guests and users can create comments"
on public.comments for insert
to anon, authenticated
with check (
  (auth.uid() is not null and auth.uid() = user_id)
  or (auth.uid() is null and user_id is null and visitor_id is not null)
);

drop policy if exists "Authors can delete their own comments" on public.comments;
create policy "Authors can delete their own comments"
on public.comments for delete
to authenticated
using (auth.uid() = user_id);