-- 妆友约：帖子图片 + 评论（文字/图片）
-- 用法：Supabase Dashboard → SQL Editor，整段粘贴执行（可重复执行）。
--
-- 说明：本站游客发帖采用「user_id 为空 + visitor_id 标识」的方式，
-- 因此评论表同样支持游客（user_id 为空）与登录用户两种身份。

-- 1) 帖子增加图片字段（imgbb 图床返回的图片地址）
alter table public.posts add column if not exists image_url text;

-- 2) 评论表
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  visitor_id text,
  author_name text,
  content text not null default '' check (char_length(content) <= 1000),
  image_url text,
  created_at timestamptz not null default now(),
  check (char_length(content) > 0 or image_url is not null),
  check (user_id is not null or visitor_id is not null)
);

create index if not exists comments_post_created_idx on public.comments (post_id, created_at);

-- 3) 行级安全策略
alter table public.comments enable row level security;

drop policy if exists "Anyone can read comments" on public.comments;
create policy "Anyone can read comments"
on public.comments for select
using (true);

drop policy if exists "Guests and users can create comments" on public.comments;
create policy "Guests and users can create comments"
on public.comments for insert
to anon, authenticated
with check (
  (auth.uid() is not null and auth.uid() = user_id)
  or (auth.uid() is null and user_id is null and visitor_id is not null)
);

drop policy if exists "Authors can delete their own comments" on public.comments;
create policy "Authors can delete their own comments"
on public.comments for delete
to authenticated
using (auth.uid() = user_id);

-- 4) 星级评分（按用户打分，满分 5 星，每人给同一用户只能打一次，可修改）
--    target_key / rater_key：登录用户为 u:<uuid>，游客为 v:<visitor_id>
create table if not exists public.ratings (
  id bigint generated by default as identity primary key,
  target_key text not null,
  target_user_id uuid references auth.users(id) on delete cascade,
  target_visitor_id text,
  rater_key text not null,
  rater_user_id uuid references auth.users(id) on delete cascade,
  rater_visitor_id text,
  stars smallint not null check (stars between 1 and 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (rater_key <> target_key),
  unique (rater_key, target_key)
);

create index if not exists ratings_target_idx on public.ratings (target_key);

alter table public.ratings enable row level security;

drop policy if exists "Anyone can read ratings" on public.ratings;
create policy "Anyone can read ratings"
on public.ratings for select
using (true);

drop policy if exists "Guests and users can rate" on public.ratings;
create policy "Guests and users can rate"
on public.ratings for insert
to anon, authenticated
with check (
  (auth.uid() is not null and rater_user_id = auth.uid())
  or (auth.uid() is null and rater_user_id is null and rater_visitor_id is not null)
);

drop policy if exists "Raters can update their own rating" on public.ratings;
create policy "Raters can update their own rating"
on public.ratings for update
to anon, authenticated
using (
  (auth.uid() is not null and rater_user_id = auth.uid())
  or (auth.uid() is null and rater_user_id is null and rater_visitor_id is not null)
)
with check (
  (auth.uid() is not null and rater_user_id = auth.uid())
  or (auth.uid() is null and rater_user_id is null and rater_visitor_id is not null)
);

-- 5) 图片存储（Supabase Storage）：帖子图片与评论图片
--    与应用同域，国内网络可正常加载（imgbb 的 i.ibb.co 在国内不可达）
insert into storage.buckets (id, name, public)
values ('post-images', 'post-images', true)
on conflict (id) do update set public = true;

drop policy if exists "Public read post-images" on storage.objects;
create policy "Public read post-images"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'post-images');

drop policy if exists "Anyone can upload post-images" on storage.objects;
create policy "Anyone can upload post-images"
on storage.objects for insert
to anon, authenticated
with check (bucket_id = 'post-images');

-- 6) 让 PostgREST 立即刷新表结构缓存
notify pgrst, 'reload schema';